### ISSUE TITLE
Compare with https:natemcmaster/CommandLineUtils

### ISSUE THREAD

**Issue by MNF** [dotnet/CliCommandLineParser#116]
Could you please in readme or wiki compare this library with https://github.com/natemcmaster/CommandLineUtils ?
What are advantages( and disadvantages) to use your library?
Why this library was created, if similar CommandLineUtils library, originally created by Microsoft, provided similar functionality?
It also will be interesting to have comparison with other similar .Net/.Net Core libraries.

**Comment by heku** [comment]
Totally agree! I'm quite confused why these similar projects were created, there should be some guide to let users choose a most suitable one.

**Comment by shaggygi** [comment]
To add to this, there seems to be related stuff coming soon.  You can learn more about it below.  I hope to see some common tools/APIs/docs that we can use and is long-term supported in the future.

[The Evolution of the .NET Framework with Kathleen Dollard](https://dotnetrocks.com/?show=1555)
[Retro Computing with .NET](https://channel9.msdn.com/Events/dotnetConf/2018/S313)

**Comment by tannergooding** [comment]
The readme was updated by @dsplaisted in https://github.com/dotnet/CliCommandLineParser/commit/b788973a620e6db7bc0458d37b449f160e40842f.

This repo is only used by the .NET CLI and new projects are recommended to use [System.CommandLine](https://github.com/dotnet/command-line-api) instead.

CC. @wli3, @KathleenDollard, @nguerrera, @jonsequitur, @livarcocc
