### ISSUE TITLE
Upgrade Arcade to 6.0

### ISSUE THREAD

**Issue by crummel** [dotnet/CliCommandLineParser#180]
Arcade in CliCommandLineParser is currently 1.0:
https://github.com/dotnet/CliCommandLineParser/blob/5faf88598629153e67f48e1d79f61884be487eb8/global.json#L6

Arcade-powered source-build requires Arcade 6.0, which is the new LTS version.  We will need to upgrade to 6.0 to support arcade-powered source-build.

cc @wli3

**Comment by wli3** [comment]
@marcpopMSFT Another unplanned infra work. We need this old parser repo alive since Template engine depends on it. Do you think we can ask Jason to do that?

**Comment by marcpopMSFT** [comment]
From MSBuild, we found upgrading arcade from 1.0 was not exactly straight forward.  We can have him try but likely there would need to be help.  How often do we update this repo and is it more of an "in case" type situation? What's the maintenance cost here and could we have Jose manage it?

**Comment by MichaelSimons** [comment]
Can this issue be closed now that #181 is in?  If not what is the remaining work?

**Comment by MichaelSimons** [comment]
@wli3 - I think this can be closed now.
