### ISSUE TITLE
Conflict between Command and Opinion with same name

### ISSUE THREAD

**Issue by wli3** [dotnet/CliCommandLineParser#63]
This happened on trying to convert dotnet help command, since there is a help command and a help opinion(--help). The repro is in [this commit](
https://github.com/wli3/CliCommandLineParser/commit/ecc734904257da00154e250873479ce976626c4e)

```csharp
        [Fact]
        public void Option_and_Command_can_have_the_same_alias()
        {
            Action a = () => new Parser(
                Command("outer", "",
                    ExactlyOneArgument(),
                    Command("inner", "",
                        ZeroOrMoreArguments()), Option("--inner", "")));
            a.ShouldNotThrow<ArgumentException>();
        }
```

**Comment by wli3** [comment]
maybe stop trim "--help" to "help" and put it into alias?

**Comment by jonsequitur** [comment]
We store it both trimmed and untrimmed. Trimmed it's used for name-based indexing and matching. I'll take a look at the repro and see what occurs to me.
