### ISSUE TITLE
NormalizeRootCommand throws if no arguments

### ISSUE THREAD

**Issue by xgalaxy** [dotnet/CliCommandLineParser#69]
The args.First() line will throw if there are no args. Additionally, maybe there should be a TreatNoArgsAsError option on the root command so that ParseResults comes back with something useful we can handle. I guess we could just check ParseResults.Tokens.Count > 0. Might be a helpful extension or property on ParseResults.

**Comment by xgalaxy** [comment]
Oh hmm. This appears to be a difference between .NET Core and .NET Full. On core the name of the executable is part of the args passed to main but on .Net Full this isn't the case. I think that explains why I suddenly started getting this exception.

**Comment by jonsequitur** [comment]
@xgalaxy, could you give a more specific usage example? `NormalizeRootCommand` should probably become internal so I'm curious whether you were using it directly. 

Thanks.

**Comment by xgalaxy** [comment]
I was not using it directly. I was simply calling Parser.Parse() and when I switched my target framework from .net core to net46 I started getting the exception. I don't think there is anything to do as I've noted above. The fix, for net46, was to get the command line arguments from the Environment since that includes the executable as part of the args.
