### ISSUE TITLE
Doesn't work with some parameter values

### ISSUE THREAD

**Issue by EmmaZhu** [dotnet/CliCommandLineParser#74]
For example I have an option defined as:

`Option SourceOption() => Option("pattern",  "",  ExactlyOneArgument());`

I cannot indicate empty string, only white spaces or "-" to it.  We have some scenarios like to transfer file with specific name like "-" or to clean up some properties with indicating empty string. It's very useful for us to allow these special strings as parameter values. 

Is there any reason why you forbid these strings?

**Comment by jonsequitur** [comment]
A few examples of the input you'd like to parse might be helpful. If I understand correctly, you want to be able to do this:

```csharp
Option SourceOption() => Option("pattern", "", ExactlyOneArgument());
var result = SourceOption().Parse("pattern  ");
Console.WriteLine(result.Diagram()); 
// actual result: [ pattern ]
// desired result: [ pattern <> ]
```

(The angle brackets in the desired result indicate an argument to the pattern option, in this case an empty string.)

A problem that I see with this approach is that the parser can't infer whether the next token is an argument to the `pattern` option or another option altogether. Here's an example:

```csharp
Option SourceOption() => Option("pattern", "", ExactlyOneArgument());
Option OtherOption() => Option("other-pattern", "", ExactlyOneArgument());
var result = new Parser(SourceOption(), OtherOption()).Parse("pattern  other-pattern");
Console.WriteLine(result.Diagram());
// [ pattern <other-pattern> ]
```
Since the `pattern` option is expecting an argument, the next token (`other-pattern`) is parsed as an argument, though it may have been intended as an option. It's ambiguous, and the parser is greedy in these cases.

One way to solve this might be to use a default argument value:

```csharp
Option SourceOption() => Option("pattern", "", ExactlyOneArgument().With(defaultValue:() =>  ""));
var result = SourceOption().Parse("pattern ");
Console.WriteLine(result.Diagram());
// [ pattern <> ]
```

Please let me know if this helps or if I'm misunderstanding.

**Comment by jonsequitur** [comment]
@EmmaZhu, have you given this a try? Thoughts?

**Comment by EmmaZhu** [comment]
@jonsequitur I just tried with your suggestions.
We are using code like following:
```
 
            Option SourceOption() =>
              Option("--source",
                      "",
                      ExactlyOneArgument().With(defaultValue: () => ""));

            Option[] SampleOptions() => new Option[] { SourceOption() };

            ParseResult parseResult = new Parser(
                   options: SampleOptions()).Parse(args);

            Console.WriteLine(parseResult.Diagram());

```
The args array is `{"--source", ""}`. It doesn't work with this array, while it works with `{"--source"}`.

I've debugged into some code and tried with making following change:

Change 
```
        public Token(string value, TokenType type)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("Value cannot be null or whitespace.", nameof(value));
            }
            Value = value;
            Type = type;
        }
```

to 

```
        public Token(string value, TokenType type)
        {
            Value = value;
            Type = type;
        }
```

Change

```
        private static bool HasPrefix(string arg) =>
            optionPrefixCharacters.Contains(arg[0]);
```
to 
```
        private static bool HasPrefix(string arg) =>
            (arg.Length > 1 && optionPrefixCharacters.Contains(arg[0]));
```

Somehow, with args array `{"--source", ""}`, it works as our expected. 
Is it possible to remove this kind of limitation?

Thanks
Emma

**Comment by jonsequitur** [comment]
@EmmaZhu In actual use, are you seeing an empty string being passed in the args array? Typically you won't see empty strings being passed in `Program.Main(params object[] args)`, nor will our `ParseResult Parse(this Parser parser, string s)` method permit them. For this reason, the `Token` constructor is there to prevent "empty" tokens from being created.

Your suggested change to `HasPrefix` is a good one.

**Comment by EmmaZhu** [comment]
The console application allows empty string as argument. I've tested above code with arguments of `--source ""`. after removing the limitation, it can output resource like `[ --source <> ]`. 

In my opinion, if the console allows empty string, there's no need for a command line parser to limit valid arguments set. 

We have a scenario in our application to clear a property when customer indicates empty string as parameter. Is that OK to remove this limitation?

**Comment by EmmaZhu** [comment]
@jonsequitur 
The console application allows empty string as argument. I've tested above code with arguments of `--source ""`. After removing the limitation, it can output result like `[ --source <> ]`. 

In my opinion, if the console allows empty string, there's no need for a command line parser to limit valid arguments set.

We have a scenario in our application to clear a property when customer indicates empty string as parameter, which has already worked this way for years on .Net framework and we'd really like to introduce the same behavior into the one on .Net Core.  If you can remove this limitation, it'd be very helpful.

**Comment by jonsequitur** [comment]
@EmmaZhu, the fix has been committed. Please take a look and let me know if this addresses the issue.

**Comment by EmmaZhu** [comment]
@jonsequitur  Thanks a lot for making this change. Just tried with latest code, it works well now.
